version: '3'

services:
  api:
    image: ghcr.io/saleor/saleor:3.15
    ports:
      - 8000:8000
    env_file:
      - backend.env
    environment:
      - DASHBOARD_URL=https://${DOMAIN}/dashboard/
      - MEDIA_URL=https://${DOMAIN}/media/
      - PUBLIC_URL=https://${DOMAIN}
      - ALLOWED_CLIENT_HOSTS=${DOMAIN}
      - ALLOWED_HOSTS=${DOMAIN},api
      - ENABLE_SSL=True
    volumes:
      - ./media:/app/media
      - ./static:/app/static
    depends_on:
      - db
      - redis

  dashboard:
    image: ghcr.io/saleor/saleor-dashboard:3.15
    ports:
      - "9000:80"
    environment:
      - API_URL=https://${DOMAIN}/graphql/
      - APP_MOUNT_URI=/dashboard/

  storefront:
    image: ghcr.io/saleor/storefront:3.15
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SALEOR_API_URL=https://${DOMAIN}/graphql/
      - NEXT_PUBLIC_STOREFRONT_URL=https://${DOMAIN}

  db:
    image: library/postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor
      - POSTGRES_DB=saleor
    volumes:
      - saleor-db:/var/lib/postgresql/data

  redis:
    image: library/redis:7.0-alpine
    ports:
      - 6379:6379
    volumes:
      - saleor-redis:/data

  nginx:
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./media:/app/media:ro
    depends_on:
      - api
      - dashboard
      - storefront

volumes:
  saleor-db:
  saleor-redis: 